server:
  port: 8080
  servlet:
    context-path: /springboot


spring:
  profiles:
    active: custom
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: henry
      password: Henry747
      url: jdbc:mysql://localhost:3306/ssm
      stat-view-servlet:
        enable: true


mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  web:
#    resources:
#      static-locations: [classpath:/henry/]
